// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDk407xsXGJYC2rmhnT3f7Uq02w_lkN2pk',
    appId: '1:699606844460:web:49f7d19f1bf63e657e3d89',
    messagingSenderId: '699606844460',
    projectId: 'todo-application-6414a',
    authDomain: 'todo-application-6414a.firebaseapp.com',
    storageBucket: 'todo-application-6414a.appspot.com',
    measurementId: 'G-MS6V9Y090H',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBMRC_1L8ohYN_m7ZPdcs3jVQoJpAVho_M',
    appId: '1:699606844460:android:edd58e665963b5367e3d89',
    messagingSenderId: '699606844460',
    projectId: 'todo-application-6414a',
    storageBucket: 'todo-application-6414a.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyD0B0W1cwjHVDQhbLt-XRMS4f_-4lZvPWk',
    appId: '1:699606844460:ios:79355f453a0a60dd7e3d89',
    messagingSenderId: '699606844460',
    projectId: 'todo-application-6414a',
    storageBucket: 'todo-application-6414a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyD0B0W1cwjHVDQhbLt-XRMS4f_-4lZvPWk',
    appId: '1:699606844460:ios:79355f453a0a60dd7e3d89',
    messagingSenderId: '699606844460',
    projectId: 'todo-application-6414a',
    storageBucket: 'todo-application-6414a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
